server:
  error:
    include-stacktrace: on_trace_param
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://:3306/realty?characterEncoding=UTF-8&serverTimezone=UTC
    username: realty
    password: 
logging:
  level:
    org.jooq: debug
    org.springframework.security.provisioning: debug
    org.springframework.security.authentication.dao: debug

