spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dev.zepinos.com:3306/realty?characterEncoding=UTF-8&serverTimezone=UTC
    username: realty
    password: realty123$
logging:
  level:
    org.jooq: debug